FROM python:3.11-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen

COPY main.py ./
COPY app/ ./app/
COPY streamlit_app/ ./streamlit_app/
COPY .streamlit/ ./.streamlit/

EXPOSE 8501

CMD ["uv", "run", "streamlit", "run", "streamlit_app/home.py", "--server.address=0.0.0.0", "--server.port=8501"]
