"""create employee and skill tables

Revision ID: 0c4f9ff0f482
Revises: acf2feb0d582
Create Date: 2026-09-14 10:46:41.084889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4f9ff0f482'
down_revision: Union[str, Sequence[str], None] = 'acf2feb0d582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employee_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('designation', sa.String(length=100), nullable=False))
    op.add_column('employees', sa.Column('experience_years', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('weekly_capacity', sa.Float(), nullable=False))
    op.add_column('employees', sa.Column('current_workload', sa.Float(), nullable=False))
    op.drop_constraint(op.f('employees_email_key'), 'employees', type_='unique')
    op.create_unique_constraint(None, 'employees', ['user_id'])
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('employees', 'email')
    op.drop_column('employees', 'experience')
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='unique')
    op.create_unique_constraint(op.f('employees_email_key'), 'employees', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('employees', 'current_workload')
    op.drop_column('employees', 'weekly_capacity')
    op.drop_column('employees', 'experience_years')
    op.drop_column('employees', 'designation')
    op.drop_column('employees', 'user_id')
    op.drop_table('employee_skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
